name: Build and push Pyton Docker immage

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]

env:
  APP_VERSION: v1.${{ github.run_number }} # Versioning based on run number ie v1.1, v1.2 etc
  CONTAINER_NAME: 'demo/worker' # replace with your container name
  WORKING_DIR: './src/' # replace with your csproj path
  CONTAINER_REGISTRY: {{ env.CONTAINER_REGISTRY }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # replace with your python version
        architecture: 'x64'
        cache: 'pip'

    - name: Install packages
      run: pip install -r requirements.txt
      working-directory: ${{ env.WORKING_DIR }}
    
    - run: pip test
      working-directory: ${{ env.WORKING_DIR }}